<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2012-04-09 17:54

$extensionPath = t3lib_extMgm::extPath('doctrine2');
return array(
	'tx_doctrine2_extbasebootstrap' => $extensionPath . 'Classes/ExtbaseBootstrap.php',
	'tx_doctrine2_manager' => $extensionPath . 'Classes/Manager.php',
	'tx_doctrine2_query' => $extensionPath . 'Classes/Query.php',
	'tx_doctrine2_queryfactory' => $extensionPath . 'Classes/QueryFactory.php',
	'tx_doctrine2_queryresult' => $extensionPath . 'Classes/QueryResult.php',
	'tx_doctrine2_domain_model_frontenduser' => $extensionPath . 'Classes/Domain/Model/FrontendUser.php',
	'tx_doctrine2_domain_model_frontendusergroup' => $extensionPath . 'Classes/Domain/Model/FrontendUserGroup.php',
	'tx_doctrine2_domain_repository_frontendusergrouprepository' => $extensionPath . 'Classes/Domain/Repository/FrontendUserGroupRepository.php',
	'tx_doctrine2_domain_repository_frontenduserrepository' => $extensionPath . 'Classes/Domain/Repository/FrontendUserRepository.php',
	'tx_doctrine2_domainobject_abstractdomainobject' => $extensionPath . 'Classes/DomainObject/AbstractDomainObject.php',
	'tx_doctrine2_domainobject_abstractentity' => $extensionPath . 'Classes/DomainObject/AbstractEntity.php',
	'tx_doctrine2_mapping_metadataservice' => $extensionPath . 'Classes/Mapping/MetadataService.php',
	'tx_doctrine2_mapping_typo3metadataservice' => $extensionPath . 'Classes/Mapping/TYPO3MetadataService.php',
	'tx_doctrine2_mapping_typo3tcametadatalistener' => $extensionPath . 'Classes/Mapping/TYPO3TCAMetadataListener.php',
	'tx_doctrine2_persistence_enablefieldsfilter' => $extensionPath . 'Classes/Persistence/EnableFieldsFilter.php',
	'tx_doctrine2_persistence_repository' => $extensionPath . 'Classes/Persistence/Repository.php',
	'tx_doctrine2_types_timestamptype' => $extensionPath . 'Classes/Types/TimestampType.php',
	'tx_doctrine2_utility_cache' => $extensionPath . 'Classes/Utility/Cache.php',
	'tx_doctrine2_utility_extension' => $extensionPath . 'Classes/Utility/Extension.php',
	'tx_doctrine2_tests_managertest' => $extensionPath . 'Tests/ManagerTest.php',
	'tx_doctrine2_tests_testcase' => $extensionPath . 'Tests/TestCase.php',
	'tx_doctrine2_tests_mapping_typo3tcametadatalistenertest' => $extensionPath . 'Tests/Mapping/TYPO3TCAMetadataListenerTest.php',
	'tx_doctrine2_tests_model_mockmetadataservice' => $extensionPath . 'Tests/Model/MockMetadataService.php',
	'tx_doctrine2_tests_model_post' => $extensionPath . 'Tests/Model/Post.php',
	'tx_doctrine2_tests_persistence_repositorytest' => $extensionPath . 'Tests/Persistence/RepositoryTest.php',
);
?>